/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

import java.util.Collections;
import java.util.Comparator;
import java.util.PriorityQueue;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void _queue() {
//        var heap = new PriorityQueue<Integer>(3, Comparator.reverseOrder());
        var heap = new PriorityQueue<Integer>();
        heap.add(3);
        heap.add(2);
        heap.add(1);
        System.out.println(heap.poll());
        heap.add(5);
        System.out.println(heap.poll());
        heap.add(6);
        System.out.println(heap.poll());
        heap.add(4);
        System.out.println(heap.poll());
        System.out.println("result " + heap.poll());
//        for (int i = 0; i < 2; i++) {
//            System.out.println(heap.peek() + " ~ " + heap.poll());
//        }
    }
}
